In [92]:
import os
import pickle
import httpx
import pandas as pd
import pycountry
import datetime
from http import HTTPStatus
import plotly.express as px
import datetime
import requests
import pandas
import json
from dotenv import load_dotenv
import geopandas as gpd
import json
import shapely
import sqlalchemy
from sqlalchemy import create_engine
import h3
import geowrangler

In [93]:
from bazze.bazze_api_client.models import query_execution
from bazze.bazze_api_client.models import counts
from bazze.bazze_api_client.api.statistics import stats_counts_by_country_get
from bazze.bazze_api_client.api.statistics import stats_counts_by_countries_get
from bazze.bazze_api_client.datatypes import Response
from bazze.bazze_api_client.api.results import results_post
from bazze.bazze_api_client.models import results
from bazze.bazze_api_client.models.query_execution import QueryExecution
from bazze.bazze_api_client.api.records import records_get
from bazze.bazze_api_client.api.records.records_get import _get_kwargs, sync, sync_detailed, _parse_response
#rename 'types.py' to 'datatypes.py'

In [94]:
#params: 
resolution=8
# delta applied to the disaster time frame to identify users
from_date_time_delta_users=-3
to_date_time_delta_users=7

# delta applied to the disaster time frame to identify records of already identified users 
from_date_time_delta_records=-3
to_date_time_delta_records=7

In [95]:
load_dotenv()
api_key = os.getenv("BAZZE_API_KEY")
headers = {"x-api-key": api_key}

In [96]:
load_dotenv()
postgrespassword = os.getenv("POSTGRES_PASSWORD")

In [97]:
from bazze.bazze_api_client import AuthenticatedClient, Client

In [98]:
client = Client(base_url="https://api.bazze.io/v1", headers=headers, timeout=120)

# GET THE LIST OF USERS BASED ON GEOFENCING

In [99]:
# NEXT STEPS

# USE ASYNC INSTEAD 
# Get users ids from geofence disaster
# get tehe non geofenced data for the shoertlist of users id that were in the geofence disaster

In [100]:
url_engine=f"postgresql://fdtn_postgres:{postgrespassword}@postgres-fdtn.postgres.database.azure.com:5432/postgres"

In [101]:
#transform polygon into geojsonand extract the disasters dates
engine = create_engine(url_engine)

sql_query = f"SELECT event_id,country,name,geometry_validated from disasters WHERE event_id = 1000072"
sql_query_date = f"SELECT event_id,fromdate,geometry_validated,todate from disasters WHERE event_id = 1000072"
disasters = gpd.read_postgis(sql_query, engine, geom_col="geometry_validated")
disasters_date = gpd.read_postgis(sql_query_date, engine, geom_col="geometry_validated")

todate=str(disasters_date['todate'][0])
fromdate=str(disasters_date['fromdate'][0])

#geojson to be used for requests.post / get
geojson_polygon=json.loads(disasters.to_json(show_bbox=False))

In [102]:
#define headers 
headers_api_get= {'x-api-key': api_key,'accept': 'application/json'}
headers_api_post= {'x-api-key': api_key,'accept': 'application/json','Content-Type': 'application/json'}

In [103]:
# GET structure 
requests.get('https://api.bazze.io/v1/users?wait=false&dryrun=false&run_large_query=false&limit=10&from_date=2023-06-01&to_date=2023-06-05&wifi_ssid=TP-LINK&country=RU&visited_country=RU' 
            , headers=headers_api_post).json()

{'detail': '429 Too Many Requests: You have exceeded the daily usage. Please try again at 2023-07-21 09:01:03.930000+00:00',
 'message': 'Too many requests'}

In [75]:
#function to use the POST structure 
def bazze_post(url, fromdate,todate,headers_api, json_application):
    query_id_json=requests.post(url+f'?wait=false&dryrun=false&run_large_query=false&limit=ALL&from_date={fromdate}&to_date={todate}' 
              , headers = headers_api_post
              , json = json_application).json()
    return query_id_json

In [80]:
#function to get the results out of a query id
def get_results(query_id_json):
    try:
        results=pandas.read_csv(requests.post('https://api.bazze.io/v1/results' 
              , headers = headers_api_post
              , json = query_id_json).json()['csv'])
    except: 
        results='Query still running'
    return results

In [ ]:
fromdate_users=str(disasters_date['fromdate'][0]+datetime.timedelta(from_date_time_delta_users))
todate_users=str(disasters_date['todate'][0]+datetime.timedelta(to_date_time_delta_users))

In [81]:
# get users based on geofencing
query_id=bazze_post('https://api.bazze.io/v1/users/geofence',fromdate_users,todate_users,headers_api_post, geojson_polygon)

In [84]:
# get the results based on query id 
df_users_geofence=get_results(query_id)

# GET THE RECORDS FROM THE USER LIST

In [88]:
# spit the total user list in smaller lists
#do not go above 1000
list_length=500

#get the full list 
full_list_users=df_users_geofence['advertising_id'].tolist()

#split the full list in list of list of len list_length
list_list_users=[full_list_users[i * list_length:(i + 1) * list_length] for i in range((len(full_list_users) + list_length - 1) // list_length )]

In [94]:
fromdate_records=str(disasters_date['fromdate'][0]+datetime.timedelta(from_date_time_delta_records))
todate_records=str(disasters_date['todate'][0]+datetime.timedelta(to_date_time_delta_records))

In [98]:
records_query_id=[]
i=0
# for each list within the list of list
for list_users in list_list_users:
    # get the query id from the records query
    
    print(i)
    #wrangling to have the list of users in the proper format - to be improved
    list_users=str(list_users)
    list_users=list_users.replace("'",'"')
    user_list_input_json='{"advertising_id":'+list_users+'}'
    user_list_input_json=json.loads(user_list_input_json)
    
    #get the query id via records/multiple call 
    query_id=bazze_post('https://api.bazze.io/v1/records/multiple',fromdate_records,todate_records,headers_api_post, user_list_input_json)
    records_query_id.append(query_id)
    i=i+1

In [ ]:
# extract and concatenate the output from the query_id
df_results=pd.DataFrame()
list_query_completed=[]
list_query_running=[]

i=0
# for each query id from the list 
for query_id in records_query_id:
    print(query_id)
    result=get_results(query_id)
    
    if type(result)==pandas.core.frame.DataFrame:
        list_query_completed.append(query_id)
        if i==0:
            df_results=result
        else:
            df_results=df_results.append(result)
        i=i+1
        
    else: 
        list_query_running.append(query_id)

print(f'there are {len(list_query_running)} queries still running')

{'QueryExecutionId': '2b63b537-7b9f-4e11-a73b-cc01d612454d'}

/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/766999684.py:3: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  results=pandas.read_csv(requests.post('https://api.bazze.io/v1/results'

{'QueryExecutionId': '3cdf7f60-0508-4d2e-957a-c33b3c935cc2'}

/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/766999684.py:3: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  results=pandas.read_csv(requests.post('https://api.bazze.io/v1/results'
/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/3701443363.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_results=df_results.append(result)

{'QueryExecutionId': '93d9611a-7523-499d-af65-f9133661c770'}

/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/766999684.py:3: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  results=pandas.read_csv(requests.post('https://api.bazze.io/v1/results'
/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/3701443363.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_results=df_results.append(result)

{'QueryExecutionId': '9c5ce28d-7b34-4d89-ae1a-99a7622c41f7'}
{'QueryExecutionId': '0ff8acd6-a0ba-4621-a689-bb2349ce4b4a'}

/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/766999684.py:3: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  results=pandas.read_csv(requests.post('https://api.bazze.io/v1/results'
/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/3701443363.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_results=df_results.append(result)

{'QueryExecutionId': 'e93ed2d9-382c-492c-8908-e9ba7218f26e'}
{'QueryExecutionId': 'ae76f704-5738-47f3-9042-e88ce7f96b5c'}

/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/766999684.py:3: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  results=pandas.read_csv(requests.post('https://api.bazze.io/v1/results'
/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/3701443363.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_results=df_results.append(result)

{'QueryExecutionId': '53af124f-b0ad-4607-8cf8-8ba39377f44b'}

/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/766999684.py:3: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  results=pandas.read_csv(requests.post('https://api.bazze.io/v1/results'
/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_3189/3701443363.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_results=df_results.append(result)

{'QueryExecutionId': '429dd0d7-166d-4921-8634-17179dc9ca97'}

In [120]:
df_results

,timestamp,latitude,longitude,country,horizontal_accuracy,user_agent,iot_signals,bazze_geohash,bazze_mgrs,bazze_gps_country,bazze_event_id,date,hash_user_id
0,2023-06-29 03:56:58.000,13.140339,123.74951,PH,8.0,NaN,NaN,wdrfzbps,51PWQ8152,PH,3a5214db4d29162022d2a8c68a94bbdac6ea172697ad64...,2023-06-29,6858597501806583072
1,2023-06-29 15:38:18.000,13.140339,123.74951,PH,8.0,NaN,NaN,wdrfzbps,51PWQ8152,PH,53c641a6174c359cb566d11890a3552fb04548de1e544a...,2023-06-29,6858597501806583072
2,2023-06-29 19:55:06.000,13.140339,123.74951,PH,7.0,NaN,NaN,wdrfzbps,51PWQ8152,PH,0f9c03221a70fa4fcbbc76851bc9d9a3de766e9a389686...,2023-06-29,6858597501806583072
3,2023-06-29 17:01:53.000,13.140339,123.74951,PH,8.2,NaN,NaN,wdrfzbps,51PWQ8152,PH,2d4ac6f478b8a1dc61a1e30a4df901161b453c2f9c4dc2...,2023-06-29,6858597501806583072
4,2023-06-29 15:24:58.000,13.140400,123.74956,PH,5.0,NaN,NaN,wdrfzbps,51PWQ8152,PH,776db03ccd9c869c67f80b25e935e76335d87fb59b04f2...,2023-06-29,6858597501806583072
...,...,...,...,...,...,...,...,...,...,...,...,...,...
810508,2023-06-23 11:06:33.000,14.544920,121.00604,PH,3.0,NaN,NaN,wdw49xcf,51PTS8508,PH,8fc6375ee3b99881dcb6ae6581eee250ea6f348dead92f...,2023-06-23,6744246600042371175
810509,2023-06-23 04:21:31.000,14.558570,121.01608,PH,3.0,NaN,NaN,wdw4cf31,51PTS8610,PH,88bda15bf82967ca36e1f0d2019cf3e082056ba8236d80...,2023-06-23,6744246600042371175
810510,2023-06-23 04:06:49.000,14.546180,121.01293,PH,3.0,NaN,NaN,wdw4c8nc,51PTS8509,PH,38f32d053d097d1badc991f9607d40fbafa6f2c29a8431...,2023-06-23,6744246600042371175
810511,2023-06-23 09:54:30.000,14.544830,121.00602,PH,1.0,NaN,NaN,wdw49xcc,51PTS8508,PH,645219927d9ce8aef2b24c4bab19c61775ae6217e18e0c...,2023-06-23,6744246600042371175
810512,2023-06-23 03:26:23.000,14.551120,121.01747,PH,3.0,NaN,NaN,wdw4cbfn,51PTS8609,PH,2a35c62e5cbe3bdba3333b155928ad0ea73326223c07d1...,2023-06-23,6744246600042371175

In [116]:
df_records_geofence=df_results

In [77]:
#test local
df_records_geofence=pd.read_csv('test_bazze_mayon.csv')

/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_8457/191416651.py:2: DtypeWarning: Columns (12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df_records_geofence=pd.read_csv('test_bazze_mayon.csv')

In [78]:
#create date and hash 
df_records_geofence['date']=pd.to_datetime(df_records_geofence['timestamp'], format="%Y/%m/%d").dt.date
df_records_geofence['hash_user_id']=df_records_geofence['advertising_id'].apply(hash)

#remove time stamp and advertising_id

df_records_geofence.drop([ 'advertising_id','bazze_device_id','publisher_id','ip_address','advertising_id_type','altitude','wifi_ssid','wifi_bssid','publisher_id','bazze_source_id'], axis=1, inplace=True)

# Calculate the daily dwelling of each person

In [67]:
#1st option: take the last record for each user x data
#2nd option: calculate an average position based on the different events

In [79]:
# keep only the last record for each user_id x date
df_records_geofence=df_records_geofence.sort_values(['hash_user_id','date','timestamp']).drop_duplicates(['hash_user_id','date'], keep='last')

In [80]:
df_records_geofence

,Unnamed: 0,timestamp,latitude,longitude,country,horizontal_accuracy,user_agent,iot_signals,bazze_geohash,bazze_mgrs,bazze_gps_country,bazze_event_id,date,hash_user_id
21705,21705,2023-06-18 05:26:01.000,13.15848,123.69432,PH,7.0,NaN,NaN,wdrfyerm,51PWQ7554,PH,89a1ae32d1fd160cf8e83c548105ce08be0588f1f30a59...,2023-06-18,-9219285133067965434
97278,97278,2023-06-07 16:38:05.000,13.34787,123.72843,PH,9.0,NaN,NaN,wdrgztbk,51PWQ7875,PH,d2421451b83ced0d9a94b8f5b12f659c21b694f857a631...,2023-06-07,-8996407298475568403
89510,89510,2023-06-08 16:30:45.000,13.34793,123.72848,PH,21.0,NaN,NaN,wdrgztbm,51PWQ7875,PH,f74a13b3d675c75ba857ffaa03db666bdfbddba29361fb...,2023-06-08,-8996407298475568403
30669,30669,2023-06-10 17:32:25.000,13.34790,123.72854,PH,2.0,NaN,NaN,wdrgztbm,51PWQ7875,PH,27bcec4e35b9fd0992aec94b87992bc7d4d21a595c7ad2...,2023-06-10,-8996407298475568403
65717,65717,2023-06-16 15:19:21.000,13.34308,123.73340,PH,29.0,NaN,NaN,wdrgzt5c,51PWQ7975,PH,912f035b3e82ad8ead473d1b4cf14e976035b0e926fa07...,2023-06-16,-8996407298475568403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124103,124103,2023-06-26 23:11:47.000,13.29735,123.79313,PH,37.0,NaN,NaN,wf258uxq,51PWQ8570,PH,5e6b37bf379500eb540916c140ca5327805248509f7b7d...,2023-06-26,9121729946711317098
129784,129784,2023-06-27 12:36:07.000,13.29730,123.79313,PH,17.0,NaN,NaN,wf258uxq,51PWQ8570,PH,98063931ca5e16639de393080fd1c747feb6d3109eeca7...,2023-06-27,9121729946711317098
153486,153486,2023-06-29 23:04:16.000,13.29742,123.79311,PH,10.0,NaN,NaN,wf258uxr,51PWQ8570,PH,460606a754c42d47084fca996d4d6171e0a8ebf5b9c382...,2023-06-29,9121729946711317098
152146,152146,2023-06-30 21:24:50.000,13.29730,123.79304,PH,12.0,NaN,NaN,wf258uxq,51PWQ8570,PH,f4ee44efb4209eb45c60e0116b2ea340bbb296355ff289...,2023-06-30,9121729946711317098
9389,9389,2023-06-22 01:36:56.000,13.15853,123.69430,PH,23.0,NaN,NaN,wdrfyerm,51PWQ7554,PH,6949d5c045cd549254406e4669472613b4cddf69df43fc...,2023-06-22,9187872663954902508

# Calculate the flow matrix for each day

In [81]:
# create 2 data flows df that will be joined to create the flow matrix
df_flow_1=df_records_geofence[['date','hash_user_id','latitude','longitude']]
df_flow_1['date_next']=df_flow_1['date']+datetime.timedelta(1)

df_flow_2=df_records_geofence[['date','hash_user_id','latitude','longitude']]

/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_8457/1301954811.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_flow_1['date_next']=df_flow_1['date']+datetime.timedelta(1)

In [51]:
#df_flow_1.join(df_flow_2, on , how='left', lsuffix='day_i', rsuffix='day_i+1', sort=False, validate=None)

In [82]:
df_flow_matrix=pd.merge(df_flow_1, df_flow_2,  how='left'
                        , left_on=['date_next','hash_user_id'], right_on = ['date','hash_user_id']
                        , suffixes=('', '_nextday')
                       )

In [83]:
df_flow_matrix=df_flow_matrix[['date','date_next','hash_user_id','latitude','longitude','latitude_nextday','longitude_nextday']]
df_flow_matrix

,date,date_next,hash_user_id,latitude,longitude,latitude_nextday,longitude_nextday
0,2023-06-18,2023-06-19,-9219285133067965434,13.15848,123.69432,NaN,NaN
1,2023-06-07,2023-06-08,-8996407298475568403,13.34787,123.72843,13.34793,123.72848
2,2023-06-08,2023-06-09,-8996407298475568403,13.34793,123.72848,NaN,NaN
3,2023-06-10,2023-06-11,-8996407298475568403,13.34790,123.72854,NaN,NaN
4,2023-06-16,2023-06-17,-8996407298475568403,13.34308,123.73340,NaN,NaN
...,...,...,...,...,...,...,...
1024,2023-06-26,2023-06-27,9121729946711317098,13.29735,123.79313,13.29730,123.79313
1025,2023-06-27,2023-06-28,9121729946711317098,13.29730,123.79313,NaN,NaN
1026,2023-06-29,2023-06-30,9121729946711317098,13.29742,123.79311,13.29730,123.79304
1027,2023-06-30,2023-07-01,9121729946711317098,13.29730,123.79304,NaN,NaN
1028,2023-06-22,2023-06-23,9187872663954902508,13.15853,123.69430,NaN,NaN

In [84]:
# fill missing next day lat/lon with previous day lat lon 
# when there is no data for the next day we assume there was no movement

df_flow_matrix.latitude_nextday=df_flow_matrix.latitude_nextday.combine_first(df_flow_matrix.latitude)
df_flow_matrix.longitude_nextday=df_flow_matrix.longitude_nextday.combine_first(df_flow_matrix.longitude)
df_flow_matrix

,date,date_next,hash_user_id,latitude,longitude,latitude_nextday,longitude_nextday
0,2023-06-18,2023-06-19,-9219285133067965434,13.15848,123.69432,13.15848,123.69432
1,2023-06-07,2023-06-08,-8996407298475568403,13.34787,123.72843,13.34793,123.72848
2,2023-06-08,2023-06-09,-8996407298475568403,13.34793,123.72848,13.34793,123.72848
3,2023-06-10,2023-06-11,-8996407298475568403,13.34790,123.72854,13.34790,123.72854
4,2023-06-16,2023-06-17,-8996407298475568403,13.34308,123.73340,13.34308,123.73340
...,...,...,...,...,...,...,...
1024,2023-06-26,2023-06-27,9121729946711317098,13.29735,123.79313,13.29730,123.79313
1025,2023-06-27,2023-06-28,9121729946711317098,13.29730,123.79313,13.29730,123.79313
1026,2023-06-29,2023-06-30,9121729946711317098,13.29742,123.79311,13.29730,123.79304
1027,2023-06-30,2023-07-01,9121729946711317098,13.29730,123.79304,13.29730,123.79304
1028,2023-06-22,2023-06-23,9187872663954902508,13.15853,123.69430,13.15853,123.69430

In [74]:
#TO BE DISCUSSED
#Fill the missing dates? for instance if we have 02/03 - 03/03 - 05/03 / should we add 04/03 to the dataset?

In [75]:
# transform lat/lon into a geometry and drop un needed columns
from shapely.geometry import Polygon, Point

#df_flow_matrix['geometry'] = [Point(xy) for xy in zip(df_flow_matrix.longitude, df_flow_matrix.latitude)] 
#df_flow_matrix['geometry_nextday'] = [Point(xy) for xy in zip(df_flow_matrix.longitude_nextday, df_flow_matrix.latitude_nextday)] 

#df_flow_matrix.drop([ 'latitude','longitude','latitude_nextday','longitude_nextday'], axis=1, inplace=True)

In [85]:
#transform geometry into h3_08

#df_flow_matrix['h3_08'] = 
df_flow_matrix['h3_08'] = [h3.geo_to_h3(y,x, resolution) for x,y in zip(df_flow_matrix.longitude, df_flow_matrix.latitude)] 
df_flow_matrix['h3_08_nextday'] = [h3.geo_to_h3(y,x, resolution) for x,y in zip(df_flow_matrix.longitude_nextday, df_flow_matrix.latitude_nextday)] 

df_flow_matrix.drop([ 'latitude','longitude','latitude_nextday','longitude_nextday'], axis=1, inplace=True)

In [90]:
# Group by 
df_flow_matrix.groupby(by=["date","date_next","h3_08","h3_08_nextday"]).count()

                                                       hash_user_id
date       date_next  h3_08           h3_08_nextday
2023-06-07 2023-06-08 8868651b0dfffff 8868651b0dfffff             1
                      8868651b29fffff 8868651b29fffff             1
                      8868651b43fffff 8868651b43fffff             1
                      8868651b45fffff 8868651b45fffff             2
                      8868651b47fffff 886865c5bbfffff             1
...                                                             ...
2023-07-10 2023-07-11 886865ced5fffff 886865ced5fffff             2
                      88694b45bbfffff 88694b45bbfffff             4
                      88694b68b1fffff 88694b68b1fffff             2
                      88694ec2d5fffff 88694ec2d5fffff             2
                      88694ed5edfffff 88694ed5edfffff             1

[805 rows x 1 columns]

# OLD

In [68]:
# define the list of users to be used in the records query
list_users=df_users_geofence['advertising_id'].tolist()
#test batch
list_users=list_users[:200]
list_users=','.join(list_users)

In [69]:
# get the records for the user id identified 
fromdate_records=str(disasters_date['fromdate'][0]+datetime.timedelta(-2))
todate_records=str(disasters_date['todate'][0]+datetime.timedelta(7))

!curl -X 'GET' \
  'https://api.bazze.io/v1/records?wait=false&dryrun=false&run_large_query=false&limit=ALL&from_date={fromdate_records}&to_date={todate_records}&advertising_id={list_users}' \
  -H 'accept: application/json' \
  -H 'x-api-key: {api_key}'

{
  "QueryExecutionId": "92d3333d-0cd0-42c5-9f78-969839486c6d"
}

In [61]:
query_records_id= '{"QueryExecutionId": "5572434c-8b7f-4e17-9b81-ff673dcc6e6a"}'

In [70]:
#compute the results
#get the list from the queryexecutionid
!curl -X 'POST' \
  'https://api.bazze.io/v1/results' \
  -H 'accept: application/json' \
  -H 'x-api-key: {api_key}' \
  -H 'Content-Type: application/json' \
  -d '{query_records_id}'

{
  "QueryExecutionId": "5572434c-8b7f-4e17-9b81-ff673dcc6e6a",
  "csv": "https://bazze.link/40cbfc",
  "json": "https://bazze.link/88021c"
}

In [94]:
df_records_geofence=pandas.read_csv('https://bazze.link/c833e4')
df_records_geofence

/var/folders/9z/sjrbpv9j1996t3_4wv3ry65c0000gn/T/ipykernel_93872/2634161463.py:1: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_records_geofence=pandas.read_csv('https://bazze.link/c833e4')

,advertising_id,advertising_id_type,timestamp,latitude,longitude,altitude,ip_address,wifi_ssid,wifi_bssid,country,horizontal_accuracy,user_agent,publisher_id,iot_signals,bazze_device_id,bazze_geohash,bazze_mgrs,bazze_gps_country,bazze_source_id,bazze_event_id
0,0CBFFCE6-5A47-4E9D-A18E-813F1AE25D50,gaid,2023-07-04 08:33:12.000,13.153143,123.695526,NaN,49.149.140.58,NaN,NaN,PH,17.0,NaN,mhpJ5DBQhTAELm0t5YdS4Q==,NaN,b2cf03d12b0e77a94deaef7f16d96b4afd8aa2c511e2ca...,wdrfyf2q,51PWQ7554,PH,cbc9ea94fcb5a20e30bbc7eb5bd51ebef70df4a0,9ca158c8fc4276437ce1f13272d93b302fb322834cb51a...
1,0CBFFCE6-5A47-4E9D-A18E-813F1AE25D50,gaid,2023-07-04 08:11:06.000,13.153150,123.695560,NaN,49.149.140.58,NaN,NaN,PH,9.0,NaN,3a26a611a00900f1dceb02157fa76fe5,NaN,b2cf03d12b0e77a94deaef7f16d96b4afd8aa2c511e2ca...,wdrfyf2q,51PWQ7554,PH,d11944eefe700d51f0f9e708670b0b921e7aedba,c0af9f1995506f9a452184902508b28d41aff36e98ecf9...
2,0C84759A-39B0-48EE-8D5F-F3C697A7F7E8,gaid,2023-07-02 11:08:39.000,13.138700,123.735300,NaN,49.145.71.58,NaN,NaN,PH,1.0,NaN,NaN,NaN,62485dca4f072afc2336002effef32c3c09408d7f30c52...,wdrfxxv6,51PWQ7952,PH,5607c245066d4c3bb5dc7e94f28b84c63a8e3adb,df42da2f2bbae5cdff22b9acd309683302a0c4911b1f1e...
3,66F5A39C-8F7B-4DED-8C11-5B135FD6768F,gaid,2023-06-22 06:36:20.000,13.145102,123.749660,NaN,45.155.89.98,NaN,NaN,PH,15.7,NaN,mhpJ5DBQhTAELm0t5YdS4Q==,NaN,8d108704478c6ae78087dc512d2e236b94ea82432281d7...,wdrfzbzx,51PWQ8153,PH,4063f77acd070788bdc73d33dfd0076bb709b1d3,720a56464773bf90fe32437b0967a6fe72e7d23e5130e3...
4,66F5A39C-8F7B-4DED-8C11-5B135FD6768F,gaid,2023-06-22 01:13:44.000,13.347851,123.735240,NaN,110.54.193.1,NaN,NaN,PH,22.0,NaN,28362,NaN,8d108704478c6ae78087dc512d2e236b94ea82432281d7...,wdrgztvh,51PWQ7975,PH,51abf54c7120f458c94b75df1869173fed4a3135,81a8149c128910922387f31f169baa22af38be80140cbb...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
161848,25B6FA7E-02A8-488B-88F7-E04549CD0342,gaid,2023-06-08 12:14:35.000,14.548310,121.105610,NaN,112.210.226.251,NaN,NaN,PH,14.0,NaN,NaN,NaN,044ab33814df806859e551633aa156291abea3d51d35bb...,wdw4gb6q,51PTS9509,PH,db2360b2ebb769a7cfaaa3f2b700b75612a67e5d,da7aaaaa8aa4047ded6fa6bf7e0d93ec7714aeab9e0570...
161849,25B6FA7E-02A8-488B-88F7-E04549CD0342,gaid,2023-06-08 02:15:40.000,14.548330,121.105640,NaN,112.210.226.251,NaN,NaN,PH,20.0,NaN,NaN,NaN,044ab33814df806859e551633aa156291abea3d51d35bb...,wdw4gb6q,51PTS9509,PH,40a04f802aab05c79567107d965dc84a27232d2f,e01544d12242985efe7a7ffb9c2a2677e930b1cf4752c2...
161850,25B6FA7E-02A8-488B-88F7-E04549CD0342,gaid,2023-06-08 10:33:52.000,14.548270,121.105570,NaN,112.210.226.251,NaN,NaN,PH,16.0,NaN,NaN,NaN,044ab33814df806859e551633aa156291abea3d51d35bb...,wdw4gb6m,51PTS9509,PH,e1d2320948e170c94535ca9d005b91f0a5368daf,9f3f0841a57167be7fd5985527a10b246d59fc659aa2f6...
161851,25B6FA7E-02A8-488B-88F7-E04549CD0342,gaid,2023-06-08 04:26:23.000,14.548277,121.105600,NaN,112.210.226.251,NaN,NaN,PH,18.0,NaN,NaN,NaN,044ab33814df806859e551633aa156291abea3d51d35bb...,wdw4gb6m,51PTS9509,PH,4d0420b526592e2a13a31424f238873c5d57f186,fd931a6c62c675c9414f872411f0ecdc1097ed64ea90e3...
161852,25B6FA7E-02A8-488B-88F7-E04549CD0342,gaid,2023-06-08 09:43:46.000,14.548300,121.105610,NaN,112.210.226.251,NaN,NaN,PH,20.0,NaN,NaN,NaN,044ab33814df806859e551633aa156291abea3d51d35bb...,wdw4gb6q,51PTS9509,PH,da0fa75ad0806e2f9dc2692f0aff45392bc7d27d,772b353edbc7a529a80d1b0a14eb8e0967f2931141d858...

In [95]:
#create date and hash 
df_records_geofence['date']=pd.to_datetime(df_records_geofence['timestamp'], format="%Y/%m/%d").dt.date
df_records_geofence['hash_user_id']=df_records_geofence['advertising_id'].apply(hash)

#remove time stamp and advertising_id

df_records_geofence.drop([ 'advertising_id','bazze_device_id','publisher_id','ip_address','advertising_id_type','altitude','wifi_ssid','wifi_bssid','publisher_id','bazze_source_id'], axis=1, inplace=True)

In [92]:
df_records_geofence

,timestamp,latitude,longitude,country,horizontal_accuracy,user_agent,iot_signals,bazze_geohash,bazze_mgrs,bazze_gps_country,date,hash_user_id
0,2023-07-04 08:33:12.000,13.153143,123.695526,PH,17.0,NaN,NaN,wdrfyf2q,51PWQ7554,PH,2023-07-04,-1875588225937754245
1,2023-07-04 08:11:06.000,13.153150,123.695560,PH,9.0,NaN,NaN,wdrfyf2q,51PWQ7554,PH,2023-07-04,-1875588225937754245
2,2023-07-02 11:08:39.000,13.138700,123.735300,PH,1.0,NaN,NaN,wdrfxxv6,51PWQ7952,PH,2023-07-02,-5096916481931887579
3,2023-06-22 06:36:20.000,13.145102,123.749660,PH,15.7,NaN,NaN,wdrfzbzx,51PWQ8153,PH,2023-06-22,3370426172100794638
4,2023-06-22 01:13:44.000,13.347851,123.735240,PH,22.0,NaN,NaN,wdrgztvh,51PWQ7975,PH,2023-06-22,3370426172100794638
...,...,...,...,...,...,...,...,...,...,...,...,...
161848,2023-06-08 12:14:35.000,14.548310,121.105610,PH,14.0,NaN,NaN,wdw4gb6q,51PTS9509,PH,2023-06-08,-1986604881691481802
161849,2023-06-08 02:15:40.000,14.548330,121.105640,PH,20.0,NaN,NaN,wdw4gb6q,51PTS9509,PH,2023-06-08,-1986604881691481802
161850,2023-06-08 10:33:52.000,14.548270,121.105570,PH,16.0,NaN,NaN,wdw4gb6m,51PTS9509,PH,2023-06-08,-1986604881691481802
161851,2023-06-08 04:26:23.000,14.548277,121.105600,PH,18.0,NaN,NaN,wdw4gb6m,51PTS9509,PH,2023-06-08,-1986604881691481802
161852,2023-06-08 09:43:46.000,14.548300,121.105610,PH,20.0,NaN,NaN,wdw4gb6q,51PTS9509,PH,2023-06-08,-1986604881691481802

In [118]:
df_records_geofence.to_csv('test_bazze_mayon.csv')

# from the records keep only the last event per day and per person

In [ ]:
# hash the ad IDs 
# use requests get / post

In [97]:
# keep only the last record for each user_id x date
df_records_geofence=df_records_geofence.sort_values(['hash_user_id','date','timestamp']).drop_duplicates(['hash_user_id','date'], keep='last')

,timestamp,latitude,longitude,country,horizontal_accuracy,user_agent,iot_signals,bazze_geohash,bazze_mgrs,bazze_gps_country,bazze_event_id,date,hash_user_id
690,2023-07-02 20:48:58.000,13.29733,123.79305,PH,25.0,NaN,NaN,wf258uxq,51PWQ8570,PH,1a42e015cf862e86c752eb4cc8bcbcc3ea47c79ecd8631...,2023-07-02,-9031570529342899449
17463,2023-07-03 10:43:45.000,13.29724,123.79317,PH,50.0,NaN,NaN,wf258uxq,51PWQ8570,PH,61f4bcb95ae3d093ff2aa7e20743175e39e7f8a2cfdf68...,2023-07-03,-9031570529342899449
58134,2023-06-12 00:55:59.000,13.13871,123.73529,PH,18.0,NaN,NaN,wdrfxxv6,51PWQ7952,PH,79c84a4217abe96d397300f5ffa41deba454e509d955bc...,2023-06-12,-8941316258867435358
68549,2023-07-02 22:49:47.000,13.25833,123.49466,PH,37.0,NaN,NaN,wdrg6jw5,51PWQ5365,PH,1f557b0568deeb2ec1be503ff12627f042e7f39b96189b...,2023-07-02,-8941316258867435358
29152,2023-06-07 18:20:44.000,13.15562,123.71518,PH,7.0,NaN,NaN,wdrfz4yt,51PWQ7754,PH,3fe5bffe70b2f0f247d7625ab7e461b3301295b8e9de66...,2023-06-07,-8886923592075452613
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81280,2023-06-16 11:26:23.000,13.13378,123.73666,PH,22.0,NaN,NaN,wdrfxwym,51PWQ7952,PH,4d5b446e67c124f79cc4d474ae979ec8418c88a47150a9...,2023-06-16,8986687457297406868
33656,2023-06-18 10:36:51.000,13.13382,123.73668,PH,39.0,NaN,NaN,wdrfxwyq,51PWQ7952,PH,94faafcab8d64420ffd49b937a6b800aa3f7dabb2e4a18...,2023-06-18,8986687457297406868
68107,2023-06-25 10:44:02.000,13.14621,123.74052,PH,19.0,NaN,NaN,wdrfzc1n,51PWQ8053,PH,532cff511e1b7af7110553a9701909932b5756540ee04c...,2023-06-25,8986687457297406868
117800,2023-07-02 03:21:50.000,13.25833,123.49460,PH,15.0,NaN,NaN,wdrg6jw5,51PWQ5365,PH,5b57baaf679990b1c6d2c2c80c2d8bfa757f4cf3f3a50a...,2023-07-02,9024281889344735284
81952,2023-06-30 20:59:02.000,13.25842,123.49470,PH,17.0,NaN,NaN,wdrg6jw5,51PWQ5365,PH,34f32d6876f7fc0a3efe8a75196cb0fc4c5387d4aef275...,2023-06-30,9051347634461073007

In [ ]:
df_records_geofence['date']